apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: review-rating-service-rest-api
  name:  review-rating-service-rest-api
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  review-rating-service-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: review-rating-service-rest-api
    spec:
      containers:
        - image: franciswebandapp/movie-booking-microservice-review-rating-service
          imagePullPolicy: IfNotPresent
          name: movie-booking-microservice-review-rating-service
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: review-rating-service-rest-api
  name: review-rating-service-rest-api
  namespace: default
spec:
  ports:
    - port: 8004
      protocol: TCP
      targetPort: 8004
  selector:
    app: review-rating-service-rest-api
  sessionAffinity: None
  type: LoadBalancer
